# Generated by Django 5.0.6 on 2024-06-24 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstatus',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Received', 'Order Received'), ('Awaiting Pickup', 'Awaiting Pickup'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
