# Generated by Django 5.0.6 on 2024-06-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_itemstatus_accepted_by_alter_purchasereceipt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemstatus',
            name='accepted_by',
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Received', 'Order Received'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
