# Generated by Django 5.0.6 on 2024-06-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_itemstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstatus',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ready for Pickup', 'Ready for Pickup'), ('Ready for Delivery', 'Ready for Delivery'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
