# Generated by Django 5.0.6 on 2024-06-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Ready for Pickup', 'Ready for Pickup'), ('Confirmed', 'Confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Completed', 'Completed')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ready for Pickup', 'Ready for Pickup'), ('Confirmed', 'Confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
